### POST Product
POST http://localhost:3000/api/shop
content-type: application/json

{
    "username": "mango",
    "password": "123456",
    "shopname": "Mango Shop",
    "address": "123 DHT",
    "role": "admin"
}

### POST Login Shop
POST http://localhost:3000/api/shop/login
content-type: application/json

{
    "username": "mango",
    "password": "123456"
}